services:
  mongodb:
    ports:
      - "27017:27017"

  api:
    build:
      context: ./api
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./api/app:/app/app:rw

  frontend:
    build:
      context: ./frontend
      target: dev
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    command: ["npm", "run", "dev"]
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"

  crawler:
    volumes:
      - ./crawler/app:/app/app:rw

  worker:
    volumes:
      - ./worker/app:/app/app:rw

